### ISSUE TITLE
Configuration error

### ISSUE THREAD

**Issue by f0rkz** [f0rkz/gameserver-daemon#6]
```
Traceback (most recent call last):
  File "gameserver-daemon.py", line 148, in <module>
    if os.path.isfile(CONFIG_FILE) and args.steamcmd:
AttributeError: 'Namespace' object has no attribute 'steamcmd'
```

Happens after configuration is ran. Config is saved, so this bug is just cosmetic.

**Comment by f0rkz** [comment]
Found another issue here:

```
Traceback (most recent call last):
  File "gameserver-daemon.py", line 226, in <module>
    if os.path.isdir(gamedir):
NameError: name 'gamedir' is not defined
```
